// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * The body of `DELETE /api/settings/account`.
 */
export type DeleteInput = { password: string, };
