// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * The body of `POST /api/forgot-password`.
 */
export type ForgotPasswordInput = { email: string, };
