// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { NotificationType } from "./NotificationType";

/**
 * The toast a redirect carries in the flash cookie; the SvelteKit root
 * layout decodes it with the exported type.
 */
export type Notification = { title: string, body: string | null, type: NotificationType, };
