// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * The body of `PUT /api/settings/password`.
 */
export type PasswordInput = { current_password: string, password: string, password_confirmation?: string, };
