// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * The body of `PUT /api/settings/profile`.
 */
export type ProfileInput = { name: string, email: string, };
