// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A mutation's answer to a fetch client: where the browser would have
 * been redirected (see `flash::respond`).
 */
export type RedirectAnswer = { redirect: string, };
