// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * The body of `POST /api/reset-password`: the link's token and email
 * plus the new password.
 */
export type ResetPasswordInput = { email: string, token: string, password: string, password_confirmation?: string, };
