// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * The account as the API exposes it; the `Serialize` key set is what
 * `GET /api/me` answers, exported to the frontend by ts-rs.
 */
export type User = { 
/**
 * JSON numbers on the wire, so `number` rather than ts-rs's `bigint`.
 */
id: number, name: string, email: string, is_admin: boolean, };
