// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * The 422 answer: the headline message and every failing field's
 * messages, the shape `frontend/src/lib/client.ts` turns into form
 * errors.
 */
export type ValidationErrors = { message: string, errors: { [key in string]: Array<string> }, };
